name: Build & Release
on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          ls -a
          mkdir -p etc/iqfiles/
          mv rockchip-iqfiles/* etc/iqfiles/
          mv etc rockchip-iqfiles/
          ls -a
          echo "testing"
          ls -a rockchip-iqfiles/
          sudo gem install fpm
          fpm -a arm64 -s dir -t deb -n rockchip-iq-openhd -v 0.2 -C rockchip-iqfiles -p rockchip-iq-openhd_VERSION_ARCH.deb
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            *.deb
      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "openhd"
          repo: "release"
          distro: "debian"
          release: "bullseye"
          republish: "true" # needed ONLY if version is not changing
          file: "*.deb"