name: Build & Release
on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          ls -a
          sudo apt install -y git ruby-dev
          sudo gem install fpm
          cd rockchip-iqfiles/rockchip-iqfiles
          mkdir -p ../etc/iqfiles/
          mv rockchip-iqfiles/* ../etc/iqfiles/
          cd ../
          rm -Rf rockchip-iqfiles
          cd ../
          fpm -a arm64 -s dir -t deb -n rockchip-iq-openhd -v 0.1 -C rockchip-iqfiles -p rockchip-iq-openhd_VERSION_ARCH.deb
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ env.artifacts_path }}/*.deb